# Generated by Django 4.1.3 on 2022-11-18 13:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_users_email_verify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='email_verify',
        ),
        migrations.AddField(
            model_name='users',
            name='verify_code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
