# Generated by Django 4.1.3 on 2022-11-18 13:52

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_users_email_verify_users_verify_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=phone_field.models.PhoneField(max_length=31, null=True, unique=True),
        ),
    ]
