# Generated by Django 4.1.3 on 2022-11-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_users_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='verify_cod',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
