# Generated by Django 4.1.3 on 2022-11-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_users_verify_cod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='verify_cod',
            field=models.BooleanField(null=True),
        ),
    ]
