# Generated by Django 4.1.3 on 2022-11-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_users_verify_cod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='verify_cod',
        ),
        migrations.AddField(
            model_name='users',
            name='verify_code_status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
