# Generated by Django 4.1.3 on 2022-12-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('volume', models.CharField(max_length=50, null=True)),
                ('price', models.CharField(max_length=50, null=True)),
                ('changes_12hour', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Значения валют',
                'verbose_name_plural': 'Значения валют',
            },
        ),
    ]
