# Generated by Django 4.1.3 on 2022-11-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuta',
            name='changes_24hour',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=10, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valuta',
            name='market_capital',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, max_length=10),
            preserve_default=False,
        ),
    ]
