# Generated by Django 4.1.3 on 2022-11-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuta', '0002_valuta_changes_24hour_valuta_market_capital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valuta',
            name='changes_24hour',
        ),
        migrations.RemoveField(
            model_name='valuta',
            name='market_capital',
        ),
        migrations.RemoveField(
            model_name='valuta',
            name='price',
        ),
        migrations.AddField(
            model_name='value',
            name='changes_24hour',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=10, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='value',
            name='market_capital',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='value',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
