# Generated by Django 4.1.3 on 2022-12-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuta', '0002_alter_value_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='price',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
