# Generated by Django 4.1.3 on 2022-11-29 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valuta', '0003_remove_valuta_changes_24hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='valut',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='valuta.valuta'),
            preserve_default=False,
        ),
    ]
