# Generated by Django 4.1.3 on 2022-12-02 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valuta', '0004_value_valut'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='value',
            options={'verbose_name': 'Значения валют', 'verbose_name_plural': 'Значения валют'},
        ),
        migrations.AlterModelOptions(
            name='valuta',
            options={'verbose_name': 'Валюты', 'verbose_name_plural': 'Валюты'},
        ),
        migrations.RenameField(
            model_name='value',
            old_name='market_capital',
            new_name='changes_12hour',
        ),
        migrations.RemoveField(
            model_name='value',
            name='changes_24hour',
        ),
    ]
