# Generated by Django 4.1.3 on 2022-12-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuta', '0005_alter_value_options_alter_valuta_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='volume',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
    ]
