# Generated by Django 4.1.3 on 2022-12-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuta', '0006_alter_value_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='changes_12hour',
            field=models.DecimalField(decimal_places=3, max_digits=10, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
