# Generated by Django 4.1.3 on 2022-12-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuta', '0007_alter_value_changes_12hour_alter_value_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='value',
            name='valut',
        ),
        migrations.AddField(
            model_name='value',
            name='title',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
