# Generated by Django 4.1.3 on 2022-12-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuta', '0009_delete_valuta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='changes_12hour',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='price',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='volume',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
