# Generated by Django 4.1.3 on 2022-12-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuta', '0010_alter_value_changes_12hour_alter_value_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='changes_12hour',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='price',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='value',
            name='volume',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
