# Generated by Django 4.1.3 on 2022-12-07 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4)),
                ('history_transactions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='owners',
            new_name='owner',
        ),
        migrations.DeleteModel(
            name='WalletInfo',
        ),
    ]
