# Generated by Django 4.1.3 on 2022-12-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_orderinfo_rename_owners_wallet_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='summ_in_dollar',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=40, null=True),
        ),
    ]
