# Generated by Django 4.1.3 on 2022-12-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_account_count_valutes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Desire',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='count_valutes',
            new_name='title_valute',
        ),
        migrations.RemoveField(
            model_name='account',
            name='summ',
        ),
        migrations.AddField(
            model_name='account',
            name='summ_in_dollar',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=40),
            preserve_default=False,
        ),
    ]
