# Generated by Django 4.1.3 on 2022-12-04 19:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('valuta', '0011_alter_value_changes_12hour_alter_value_price_and_more'),
        ('wallet', '0003_delete_desire_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='Wallet',
        ),
    ]
