# Generated by Django 4.1.3 on 2022-12-05 17:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('valuta', '0011_alter_value_changes_12hour_alter_value_price_and_more'),
        ('wallet', '0004_rename_account_wallet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wallet',
            new_name='Wallets',
        ),
    ]
