# Generated by Django 4.1.3 on 2022-12-05 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0005_rename_wallet_wallets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallets',
            name='owners',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wallets',
            name='summ_in_dollar',
            field=models.DecimalField(decimal_places=3, max_digits=40, verbose_name='сумма'),
        ),
    ]
