# Generated by Django 4.1.3 on 2022-12-05 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valuta', '0011_alter_value_changes_12hour_alter_value_price_and_more'),
        ('wallet', '0006_alter_wallets_owners_alter_wallets_summ_in_dollar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallets',
            name='summ_in_dollar',
            field=models.DecimalField(decimal_places=3, max_digits=40, null=True, verbose_name='сумма'),
        ),
        migrations.AlterField(
            model_name='wallets',
            name='title_valute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='valuta.value'),
        ),
    ]
