# Generated by Django 4.1.3 on 2022-12-08 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletvalutes',
            name='amount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet'),
            preserve_default=False,
        ),
    ]
