# Generated by Django 4.1.3 on 2022-12-05 20:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('valuta', '0011_alter_value_changes_12hour_alter_value_price_and_more'),
        ('wallet', '0007_alter_wallets_summ_in_dollar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('summ', models.IntegerField()),
                ('valut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valuta.value')),
            ],
        ),
        migrations.CreateModel(
            name='WalletsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4)),
                ('history_transactions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.transactions')),
            ],
        ),
    ]
