# Generated by Django 4.1.3 on 2022-12-08 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_walletvalutes_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletvalutes',
            name='amount',
        ),
    ]
